"""add status_message to jobs

Revision ID: 38590253311a
Revises: 3a2b1c4d5e6f
Create Date: 2025-06-05 11:50:28.199431+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38590253311a'
down_revision = '3a2b1c4d5e6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('status_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'status_message')
    # ### end Alembic commands ###