"""Initial migration

Revision ID: 28a075bb7af8
Revises: 
Create Date: 2025-06-04 10:27:56.455913+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28a075bb7af8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instance_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vast_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('gpu_type', sa.String(length=100), nullable=False),
    sa.Column('gpu_count', sa.Integer(), nullable=False),
    sa.Column('cpu_count', sa.Integer(), nullable=False),
    sa.Column('ram_gb', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('cost_per_hour', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('benchmark_data', sa.JSON(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vast_id')
    )
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hash_type', sa.String(length=50), nullable=False),
    sa.Column('hash_file_path', sa.String(length=500), nullable=True),
    sa.Column('word_list', sa.String(length=500), nullable=True),
    sa.Column('custom_attack', sa.Text(), nullable=True),
    sa.Column('rule_list', sa.String(length=500), nullable=True),
    sa.Column('time_started', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hard_end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_finished', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('READY_TO_START', 'QUEUED', 'INSTANCE_CREATING', 'RUNNING', 'PAUSED', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=True),
    sa.Column('pot_file_path', sa.String(length=500), nullable=True),
    sa.Column('log_file_path', sa.String(length=500), nullable=True),
    sa.Column('instance_type', sa.String(length=100), nullable=True),
    sa.Column('instance_id', sa.String(length=100), nullable=True),
    sa.Column('estimated_time', sa.Integer(), nullable=True),
    sa.Column('actual_cost', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('job_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('local_path', sa.String(length=500), nullable=True),
    sa.Column('s3_key', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_files_job_id'), 'job_files', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_files_job_id'), table_name='job_files')
    op.drop_table('job_files')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('system_settings')
    op.drop_table('instance_types')
    # ### end Alembic commands ###