"""change_description_to_text_in_wordlist_metadata

Revision ID: a5f4cb52560f
Revises: f993e7d8d3ad
Create Date: 2025-06-10 16:16:54.998938+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5f4cb52560f'
down_revision = 'f993e7d8d3ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###