"""add_required_disk_gb_to_jobs

Revision ID: f29603d24dd5
Revises: 38590253311a
Create Date: 2025-06-09 16:24:51.196744+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f29603d24dd5'
down_revision = '38590253311a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('required_disk_gb', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'required_disk_gb')
    # ### end Alembic commands ###