"""add_wordlist_metadata_catalog

Revision ID: d35b6b8d89cd
Revises: f29603d24dd5
Create Date: 2025-06-09 20:50:09.082296+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd35b6b8d89cd'
down_revision = 'f29603d24dd5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wordlist_metadata',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('s3_key', sa.String(length=500), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('compressed_size', sa.BigInteger(), nullable=False),
    sa.Column('uncompressed_size', sa.BigInteger(), nullable=True),
    sa.Column('line_count', sa.BigInteger(), nullable=True),
    sa.Column('compression_format', sa.String(length=10), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('estimated_crack_time_md5', sa.Float(), nullable=True),
    sa.Column('popularity_score', sa.Integer(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('requires_premium', sa.Boolean(), nullable=True),
    sa.Column('md5_hash', sa.String(length=32), nullable=True),
    sa.Column('sha256_hash', sa.String(length=64), nullable=True),
    sa.Column('last_verified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wordlist_metadata_s3_key'), 'wordlist_metadata', ['s3_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wordlist_metadata_s3_key'), table_name='wordlist_metadata')
    op.drop_table('wordlist_metadata')
    # ### end Alembic commands ###