"""remove_s3_key_from_wordlist_metadata

Revision ID: f993e7d8d3ad
Revises: 7e79ca7f27a0
Create Date: 2025-06-09 21:14:14.257878+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f993e7d8d3ad'
down_revision = '7e79ca7f27a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wordlist_metadata_s3_key', table_name='wordlist_metadata')
    op.drop_column('wordlist_metadata', 's3_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wordlist_metadata', sa.Column('s3_key', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.create_index('ix_wordlist_metadata_s3_key', 'wordlist_metadata', ['s3_key'], unique=False)
    # ### end Alembic commands ###