"""remove_unique_constraint_from_wordlist_metadata_s3_key

Revision ID: 7e79ca7f27a0
Revises: d35b6b8d89cd
Create Date: 2025-06-09 21:07:24.759458+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e79ca7f27a0'
down_revision = 'd35b6b8d89cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wordlist_metadata_s3_key', table_name='wordlist_metadata')
    op.create_index(op.f('ix_wordlist_metadata_s3_key'), 'wordlist_metadata', ['s3_key'], unique=False)
    op.drop_column('wordlist_metadata', 'estimated_crack_time_md5')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wordlist_metadata', sa.Column('estimated_crack_time_md5', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_wordlist_metadata_s3_key'), table_name='wordlist_metadata')
    op.create_index('ix_wordlist_metadata_s3_key', 'wordlist_metadata', ['s3_key'], unique=False)
    # ### end Alembic commands ###